// <auto-generated />
using System;
using Loteria.API.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Loteria.API.Migrations
{
    [DbContext(typeof(LoteriaContext))]
    partial class LoteriaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Loteria.API.Entidade.Loteria", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("CodigoLoteria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("LOTERIA");

                    b.Property<int>("Concurso")
                        .HasMaxLength(8)
                        .HasColumnType("int")
                        .HasColumnName("CONCURSO");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_CADASTRO");

                    b.Property<DateTime?>("DataProximoConcurso")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_PROXIMO_CONCURSO");

                    b.Property<string>("Dezena1")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("DEZENA1");

                    b.Property<string>("Dezena2")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("DEZENA2");

                    b.Property<string>("Dezena3")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("DEZENA3");

                    b.Property<string>("Dezena4")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("DEZENA4");

                    b.Property<string>("Dezena5")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("DEZENA5");

                    b.Property<string>("Dezena6")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("DEZENA6");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("RESULTADO");

                    b.HasKey("Id")
                        .HasName("ID");

                    b.HasIndex("Concurso", "CodigoLoteria")
                        .IsUnique();

                    b.ToTable("LOTERIA", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
