name: CD/CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get latest commit hash
        id: get_commit_hash
        run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"        

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src
          dockerfile: Dockerfile
          push: false
          tags: guidi/loteria-api:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./src
          dockerfile: Dockerfile
          push: true
          tags: guidi/loteria-api:${{ steps.get_commit_hash.outputs.commit_hash }}
